#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2034,SC2154,SC2153,SC2119,SC2120,SC1090
# (variables, assignments and function calls span the sourced lib/ modules, so
#  cross-module references are invisible to per-file analysis)
# TinkerGame library module -- sourced by the "tinkergame" entry point. Do not execute directly.

function howto {
	echo "========================="
	echo "$PROGNAME $PROGVERS"
	echo "========================="
	echo "Usage: $PROGCMD [options]..."
	echo ""
	echo "where options include:"
	echo "  (All <path> args must be absolute paths)"
	echo ""
	echo "    addcustomproton|acp <path>       Adds local custom Proton to"
	echo "                                       the internal list from dialog"
	echo "                                       or directly from <path>"
	echo "    addnonsteamgame|ansg <args>      Add a $NSGA to Steam"
	echo "                                       opens gui without args"
	echo ""
	echo "     Ensure the Steam Client is closed before adding shortcuts."
	echo "     <args>:                          for cli min arg is'-ep'"
	echo "     -an=|--appname=	                 App Name - optional"
	echo "     -ep=|--exepath=                  Full gamepath required"
	echo "     -sd=|--startdir=                 Start Dir - optional"
	echo "     -ip=|--iconpath=                 Icon Path - optional"
	echo "     -lo=|--launchoptions             Game Launch Options - optional"
	echo "     -hd=|--hide=                     Hide Game - optional*"
	echo "     -adc=|--allowdesktopconf=        Allow Desktop Conf - optional"
	echo "     -ao=|--allowoverlay=             Allow Overlay - optional"
	echo "     -vr=|--openvr=                   OpenVR - optional*"
	echo "     -t=|--tags=                      Tags - quoted, comma-separated - optional"
	echo "     -stllo|--stllaunchoption         Use '${PROGCMD} %command%' as Launch Option - optional"
	echo "     -ct=|--compatibilitytool=        Specify the name of the compatibility tool to use - optional"
	echo "                                       Can specify 'default' to use the global Steam Compatibility Tool"
	echo "     -hr=|--hero=                     Hero Art path    - Banner used on the Game Screen (3840x1240 recommended) - optional"
	echo "     -lg=|--logo=                     Logo Art path    - Logo that gets displayed on Game Screen (16:9 recommended) - optional"
	echo "     -ba=|--boxart=                   Box Art path     - Cover art used in the library (600x900 recommended) - optional"
	echo "     -tf=|--tenfoot=                  Tenfoot Art path - Small banner used for recently played game in library (600x350 recommended) - optional"
	echo "     --copy                            Copy art files to Steam Grid folder (default) - optional"
	echo "     --link                            Symlink art files to Steam Grid folder - optional"
	echo "     --move                            Move art files to Steam Grid folder - optional"
	echo "     --auto-artwork                  Use image files in the game EXE directory with names 'hero', 'logo', 'boxart', 'tenfoot' - optional"
	echo "                                       This will respect the copy method flags above."
	echo "                                       Note also that this will return for any files assumed to be images, even if Steam doesn't support the image format."
	echo "     --use-steamgriddb               Enable searching SteamGridDB for game artwork"
	echo "                                      By default, if no other options are provided, it will search SteamGridDB using --appname"
	echo "                                      If -sgid, -sgai, or -sgnm are passed, this option will automatically be enabled"
	echo "     --steamgriddb-game-name=       Custom name to search and download grid artwork on, if no ID is found it will fall back to Steam AppID OR SteamGridDB Game ID"
	echo "                                      If no IDs are provided and no match is found on the given name, no artwork will be downloaded"
	echo "     --steamgriddb-steam-appid=     Steam AppID to search and download grid artwork on, this will be used instead of SteamGridDB Game ID if both are passed"
	echo "     --steamgriddb-game-id=         Game ID from SteamGridDB to search and download grid artwork on"
	echo "                                        This requires a SteamGridDB API key. See the SteamGridDB wiki page for guidance on how to generate and supply it."
	echo "    backup <value>                   Backup found '$STUS' files"
	echo "                                       (for 'SteamAppID' or 'all')"
	echo "    block                            Opens the category Block selection menu"
	echo "    cleardeckdeps                    Remove downloaded Steam Deck dependencies, allowing them to"
	echo "    cleargamegrids <arg>            Remove downloaded game grids based on <arg>, which should be one of the following"
	echo "        <appid>                       Remove artwork for game with specific AppID, ex: 787480"
	echo "        all                           Remove ALL grid artwork by removing entire Steam Grids folder"
	echo "                                      update on next launch (This option is only applicable to SteamOS 3.X)"
	echo "    compat <cmd>                     Will (add|del|get) ${PROGNAME,,} as"
	echo "                                       Steam compatibility tool"
	echo "                                       under 'STEAMCOMPATOOLS'"
	echo "    configdir                        Open the TinkerGame config directory with xdg-open"
	echo "    conty up|update                  Update the bundled Conty runtime"
	echo "    createappinfo|cai <id|i|o>       Create raw appinfo for <id>"
	echo "                                      or for 'installed|i' or 'owned|o' games"
	echo "                                      Append any arg to update the raw file"
	echo "                                      (takes a long time for many games!)"
	echo "    createappinfometa|caim <id|i|o>  Read data from raw appinfo for <id>"
	echo "                                      or for 'installed|i' or 'owned|o' games"
	echo "                                      and write to game metadata."
	echo "                                      Append any arg to update the metadata"
	echo "                                      (takes a long time for many games!)"
	echo "    createcompatdata|ccd <gameid><gui> (Re-)create compatdata for <gameid>"
	echo "                                       open <gui> to configure custom programs"
	echo "    createdesktopicon|cdi <game><id> Create desktop icon for <game>"
	echo "                                       <game> is the gameid or"
	echo "                                       with available meta game title"
	echo "                                       0=only internally"
	echo "                                       1=on the desktop"
	echo "                                       2=for the application menu"
	echo "                                       3=for desktop and application menu"
	echo "    createfirstinstall|cfi <gameid>  Open gui to create a Steam First Time Setup"
	echo "    <a|c|r|file> (see wiki)            file for game <gameid>"
	echo "    ${DPRS,}|dprs                    Prepare/launch ${DPRS}"
	echo "    dlcustomproton|dcp <url|l>       Download/install custom Proton"
	echo "                                       - from filerequester"
	echo "                                       - directly from <url>"
	echo "                                       - the 'latest|l' GE version"
	echo "                                       - 'latestge|lge' for Proton-GE"
	echo "                                       - 'latesttkg|ltkg' for Proton-TKG"
	echo "    dlwine|dw <url or latest|l>      Download/install Wine archive"
	echo "                                       from filerequester or"
	echo "                                       automatically the latest|l version or"
	echo "                                       directly from <url>"
	echo "    dotnet <pfx> <wine>              Install dotnet into a Wineprefix"
	echo "    dxvkhud|dxh <gameid>             Pick a DXVK HUD layout for <gameid>"
	echo "    editor <value>                   Opens the editor menu"
	echo "                                       (for 'SteamAppID' or 'last')"
	echo "    fav <value>                      Opens the favorite menu"
	echo "                                       (for 'SteamAppID' or 'last')"
	echo "    gamefiles|gf <gameid>            Opens menu for opening <gameid> files"
	echo "    gamescope|gs <gameid>            Gamescope config-menu for <gameid>"
	echo "    (get commands work most reliably for games previously launched with ${PROGNAME,,}:)"
	echo "    getcompatdata|gc <gameid/title>  Print the Game compatdata path"
	echo "    getexe|ge <gameid/title>         Print the Game Exe for <gameid/title>"
	echo "    getgamedir|gg <gameid/title>     Print the Game install directory with game name and AppID"
	echo "                  only                 Only display install directory"
	echo "    getid|gi|gid <gametitle>         Print the SteamAppId for <gametitle>"
	echo "    getsteamgriddbid|sgdbid <title>  Get SteamGridDB Game ID for <title>"
	echo "    getslr <gameid>                  Fetch the required Steam Linux Runtime for <gameid>'s TinkerGame Proton version"
	echo "               native                  (optional) get the native Steam Linux Runtime"
	echo "    gettitle|gt <gameid>             Print the Game Title for <gameid>"
	echo "    help                             Show this help text"
	echo "    helpurl|hu <gameid>              Open the help URL menu for <gameid>"
	echo "    hedgemodmanager|hmm              HedgeModManager"
	echo "            install|i                  install latest stable HedgeModManager"
	echo "            download|d <channel>       download latest HedgeModManager release (stable or nightly)"
	echo "                                        defaults to stable"
	echo "            start|s <channel>          start HedgeModManager"
	echo "                                        automatically downloads and installs latest stable if <channel>"
	echo "                                        is not provided"
	echo "            url|u <url>              Download a GameBanana mod using MineType URL"
	echo "                                      Note that this will *not* work with regular browser URLs"
	echo "            desktopfile|df           (Re-)create .desktop files for HedgeModManager"
	echo "            list-supported           List games supported by HedgeModManager"
	echo "            list-installed           List installed games with HedgeModManager support"
	echo "            list-owned               List owned games on Steam with HedgeModManager support"
	echo "            resetmime                (Re)set MimeType and application menu entries"
	echo "            uninstall                Remove HedgeModManager downloads folder, desktop files and Wineprefix"
	echo "                                      Note that this will not remove your mods or installed Winetricks"
	echo "    lang=<option>                    Mostly to get translated configs on inital setup."
	echo "                                      <option> can be a language file name without suffix or an path to a valid language file"
	echo "    launcher <args>                  Start the Game Launcher"
	echo "             COLLECTION                Show only installed games from Steam collection COLLECTION"
	echo "             menu                      Open Steam Collection Menu"
	echo "             last                      Open last Game as 'Menu'"
	echo "             auto                      Create/Download data for all installed games first"
	echo "             update                    ReCreate all Collection Menus"
	echo "                                       Can be combined with auto"
	echo "    list <owned|installed|non-steam>   List info on <owned|o,installed|i,non-steam|nsg> games"
	echo "         <id|name|path|count|full>     Optionally specify whether you want to see"
	echo "                                        each game's <id|name|path|count|full>"
	echo "                                       NOTE: Non-Steam Games will NOT be included in <installed,owned>,"
	echo "                                        they will only show up for <non-steam|nsg>"
	echo "    listproton|lp                    List name and path of all Proton versions known to TinkerGame"
	echo "         name|n                        Only list the Proton version names"
	echo "         path|p                        Only list paths to the Proton versions"
	echo "    meta                             Generates/Updates metadata"
	echo "                                       for all installed games"
	echo "    mo2                              Mod Organizer 2"
	echo "         create-instance|ci <id>     create MO2 instance for <id>"
	echo "         download|d                  download latest MO2 release"
	echo "         getprefix|gp                Output path to MO2 prefix"
	echo "         install|i                   install MO2 (includes download)"
	echo "          <path>                      optional path for custom MO2 installer executable"
	echo "         list-supported|ls           list games supported by MO2"
	echo "         list-installed|li           list installed games supported by MO2"
	echo "         resetmime                   (Re)set MimeType and application menu entries"
	echo "         start|s                     start MO2 (includes download+install)"
	echo "         url|u <url>                 open nxm url with MO2"
	echo "         winecfg                     Run Winecfg with MO2 Wine in MO2 prefix"
	echo "         winetricks|wt               Run Winetricks with MO2 Wine in MO2 prefix"
	echo "    opengridfolder|ogf               Open the Steam Grid folder where custom game artwork is stored using xdg-open"
	echo "    openissue|oi                     Opens issue tracker on GitHub in default browser"
	echo "    onetimerun|otr <gameid>          Opens One-Time Run menu for running a one-off executable in <gameid>'s Wineprefix"
	echo "                                       Optionally takes command-line parameters to run without the GUI. Note that only"
	echo "                                       the path to the one-time exe is required, STL will try to infer the other options"
	echo "                                       such as Proton version where possible."
	echo "         <args>:"
	echo "         --exe=                        Absolute path to the One-Time executable (can be Windows or Linux executable)"
	echo "         --proton=                     Name of the Proton version to use (see tinkergame lp). Defaults to Per-Game Proton version ('USEPROTON'), ignored if not Windows executable"
	echo "         --workingdir=                 Working directory to launch the executable from"
	echo "         --useexedir                   Use the same directory as the executable as the working directory (overrides --workingdir)"
	echo "         --args=                       Arguments to append to the end of the executable launch"
	echo "         --forceproton                 Use Proton to run executable even if TinkerGame detects doesn't detect it as a Windows executable"
	echo "         --useslr                      Use the Steam Linux Runtime to run the application, if available (uses SLR specified by Proton version or native Linux Steam Linux Runtime)"
	echo "         --save                        Save given configuration for use in the One-Time Run GUI for this game in future"
	echo "         --default                     Restore all saved One-Time Run values to default"
	echo "    play <gameid>                    Start game with id <gameid> directly"
	echo "    proton|p <title> <X>             Start and/or create <title> with proton"
	echo "                                       without using steam."
	echo "                                       Optional <X> opens gui"
	echo "    proton|p list                    Update the list of all available proton versions"
	echo "    set <var> <for> <value>          Change configuration settings, either per-game (<AppID>), for all games (<all>),"
	echo "                                      or in the Global config (<global>)"
	echo "                                       Example:"
	echo "      set RUN_REPLAY all 1               Set RUN_REPLAY for all games to 1"
	echo "      set STLEDITOR global \"/path\"     Set the path to the STLEDITOR binary in the global config"
	echo "    setgameart|sga <gameid> <args>   Set the artwork for various games by their AppID using absolute paths"
	echo "                                      Passing no args will open a GUI"
	echo "                                      By default, given artwork will be copied to the Steam Grid folder"
	echo "                                      Note that only ONE of the copy/link/move options should be used"
	echo "      <args>:                           "
	echo "      -hr=|--hero=                     Hero Art path    - Banner used on the Game Screen (3840x1240 recommended)"
	echo "      -lg=|--logo=                     Logo Art path    - Logo that gets displayed on Game Screen (16:9 recommended)"
	echo "      -ba=|--boxart=                   Box Art path     - Cover art used in the library (600x900 recommended)"
	echo "      -tf=|--tenfoot=                  Tenfoot Art path - Small banner used for recently played game in library (600x350 recommended)"
	echo "      --copy                            Copy art files to Steam Grid folder"
	echo "      --link                            Symlink art files to Steam Grid folder"
	echo "      --move                            Move art files to Steam Grid folder"
	echo "    settings <value>                 Opens the $SETMENU"
	echo "    sort                             Open the category sort menu"
	echo "    src                              Shortcut '$STERECO'"
	echo "    steamdeckcompat <gameid>         Get information about Steam Deck compatibility for <gameid>"
	echo "                                       Will work offline if the information has been fetched before"
	echo "    steamgriddb|sgdb <appid/args>    Download most relevant artwork from SteamGridDB based on Steam AppID or SteamGridDB Game ID"
	echo "                                      Attempts to search for and download hero, logo, and boxart from SteamGridDB, and can optionally"
	echo "                                      apply this artwork to the game in your Steam library, by giving it the AppID of the game to use"
	echo "                                      in the filename."
	echo "                                       This setting uses preferences specified on Global Menu under SteamGridDB options, such as"
	echo "                                       dimensions, and how to manage existing files (though an override can be specified for how"
	echo "                                       to manage existing artwork files)."
	echo "     Pass an AppID instead of the below args to open a GUI for selecting game artwork."
	echo "      <args>:"
	echo "      --search-id=                     Steam AppID or SteamGridDB Game ID to search for (ex: AppID 22330 or Game ID 5258102)"
	echo "      --search-name=                   Search SteamGridDB with a name and return the best-match Game ID, and use --nonsteam automatically."
	echo "                                        You must pass '--filename-appid' when using this option, otherwise artwork will use the wrong ID"
	echo "      --filename-appid=                Steam AppID to use when naming the file, only required when searching on Game ID or Game Name so the artwork is applied to the correct Shortcut"
	echo "      --steam                          The Search ID passed is for a Steam AppID (default)"
	echo "      --nonsteam                       The Search ID passed is for a SteamGridDB Game ID"
	echo "      --apply                          Apply the downloaded game artwork to the Steam game (if not set, artwork will be downloaded to TinkerGame Grid directory only)"
	echo "      --no-apply                       Don't apply the downloaded game artwork (artwork will be downloaded to TinkerGame Grid directory only)"
	echo "      --skip-existing                  Skip setting artwork for this game if it already has custom artwork"
	echo "      --replace-existing               Replace existing artwork files for this game -- they cannot be recovered later"
	echo "      --backup-existing                Backup existing artwork files for this game before replacing them, so they can be restored"
	echo ""
	echo "    steamworksshared|sws <opts>      Steamworks Shared:"
	echo "      <opts>:                          Options:"
	echo "      <l>                              List packages - or"
	echo "      <i>                              Install package with options:"
	echo "      <packagename>                    - packagename"
	echo "      <SteamAppID or pfx>              - SteamAppID or pfx path"
	echo "      <wine binary>                    - Optional wine binary path"
	echo "    update <value>                   Updates <value>:"
	echo "           gamedata <SteamAppID>       Updates missing desktopfiles"
	echo "                                       and pictures of installed games"
	echo "                                       or only from <SteamAppID>"
	echo "           grid <SteamAppID>         Update Steam Grid for installed game(s)"
	echo "                                       optional argument either a SteamAppID,"
	echo "                                       'owned', 'installed', or 'nonsteam|shortcut'"
	echo "                                       (default is 'installed')"
	echo "           allgamedata                 The same as above for"
	echo "                                       all games in $SCV"
	echo "           shaders <shadername>        all enabled shaders or <shadername>"
	echo "                                       'list' to list shaders"
	echo "                                       'repos' to update used shader repos"
	echo "           gameshaders <opt1> <opt2|3> open shader selection for dir <opt1>,"
	echo "                                       for last gamedir when <opt1> is empty"
	echo "                                       enable repo <opt1> for dir <opt2>"
	echo "                                        with empty <opt3> or <opt3>=enable"
	echo "                                       disable repo <opt1> for dir <opt2>"
	echo "                                        with  <opt3>=disable"
	echo "                                       block repo <opt1> with <opt2>=block"
	echo "                                       unblock repo <opt1> with <opt2>=unblock"
	echo "           reshade <version>           (re)-download ReShade (version)"
	echo "    version                          Output the program version"
	echo "    ${VTX} <value>                   ${VTX^} commandline options"
	echo "                                      ${VTX} download, install, and start can optionally take"
	echo "                                       a version tag to download."
	echo "                                      Ex: tinkergame vortex start v1.8.0"
	echo "           getprefix|gp                Output path to Vortex prefix"
	echo "           install                     Installs ${VTX^}"
	echo "           list-supported|ls           List all ${VTX^}-supported Steam Game IDs"
	echo "                                       (offline - ${VTX^} needs to be installed)"
	echo "           list-online|lo              List ${VTX^}-supported games found online"
	echo "           list-owned|low              List owned games with ${VTX^} support"
	echo "           list-installed|li           List installed Games with ${VTX^} support"
	echo "           games                       Gui to en/disable ${VTX^} for supported game"
	echo "           symlinks                    Gui showing ${VTX^} symlinks"
	echo "           start                       Starts ${VTX^}"
	echo "           url|u <url>                 Open nxm url with ${VTX^}"
	echo "           getset                      Show config of installed ${VTX^}"
	echo "           reset                       Reset all autodetected settings in ${VTX^}"
	echo "           stage <path>                Add ${VTX^} stage via dialog"
	echo "                                        or directly the one given in <path>"
	echo "           resetmime                   (Re)set MimeType and application menu entries"
	echo "           winecfg                     Run Winecfg with ${VTX^} Wine in ${VTX^} prefix"
	echo "           winetricks|wt               Run Winetricks with ${VTX^} Wine in ${VTX^} prefix"
	echo "    vr <windowname> <SteamAppID> <s> Start SBS-VR mode for <windowname>"
	echo "                                       and game <SteamAppID>"
	echo "                                       's'ave windowname for the game"
	echo "    waitrequester|wr e|s|u           <e>nable the waitrequester for the launched game"
	echo "                                       (no effect if already enabled)"
	echo "                                     <s>kip the waitrequester temporarily"
	echo "                                     <u>nskip the temporary waitrequester skip"
	echo "    noty [text]                      Show a test notification"
	echo "    pdb <gameid>                     Look up <gameid> on ProtonDB"
	echo "    pickwin|pw <gameid> <win>        Pick/save a window name for SBS-VR"
	echo "    runwinecfg|onetimewinecfg|otwcfg [gameid]   Run Winecfg once in a game's prefix"
	echo "    runwinetricks|onetimewinetricks|otwt [gameid] Run Winetricks once in a game's prefix"
	echo "    ${SPEK,,} download|dl            Download ${SPEK}"
	echo "    winedebugchannel|wdc <gameid>    Set Wine debug channels for <gameid>"
	echo "    winetricks|wt <gameid>           Launch Winetricks for <gameid>'s prefix"
	echo "    wiki <page>                      Opens the wiki <page> in yad"
	echo "    yad <yad binary> <opt>           Configure the used Yad binary"
	echo "                                       <yad binary> can be either"
	echo "                                       <absolute/path>"
	echo "                                       <conty>"
	echo "                                       <ai> or <appimage> plus optional <opt>:"
	echo "                                       <opt> can be either"
	echo "                                         <absolute/path/to/a/yad/appimage>"
	echo "                                         <http/s/yad/appimage/download/url>"
	echo "                                       (see Wiki for details)"
}

