#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2034,SC2154,SC2153,SC2119,SC2120,SC1090
# (variables, assignments and function calls span the sourced lib/ modules, so
#  cross-module references are invisible to per-file analysis)
# TinkerGame library module -- sourced by the "tinkergame" entry point. Do not execute directly.

# Help text. The command listing is generated from data/commands.def via the
# registry (lib/cli/registry.sh); the multi-line usage details below are
# static and must be kept in sync with the dispatch handlers manually.

function howto {
	echo "========================="
	echo "$PROGNAME $PROGVERS"
	echo "========================="
	echo "Usage: $PROGCMD [options]..."
	echo ""
	echo "where options include:"
	echo "  (All <path> args must be absolute paths)"
	echo ""

	local TG_H_GROUP TG_H_VERB TG_H_LINE
	if [ "$TG_CMD_REGISTRY_LOADED" -eq 1 ] && [ "${#TG_CMD_GROUPS[@]}" -gt 0 ]; then
		for TG_H_GROUP in "${TG_CMD_GROUPS[@]}"; do
			if [ "$TG_H_GROUP" == "General" ]; then
				while IFS= read -r TG_H_VERB; do
					[ -z "$TG_H_VERB" ] && continue
					if [ -n "$(tgCmdArgs "General" "$TG_H_VERB")" ]; then
						echo "    $TG_H_VERB $(tgCmdArgs "General" "$TG_H_VERB")"
					else
						echo "    $TG_H_VERB"
					fi
					TG_H_LINE="$(tgCmdSummary "General" "$TG_H_VERB")"
					[ -n "$TG_H_LINE" ] && echo "        $TG_H_LINE"
				done <<< "$(tgCmdGroupVerbs "General")"
			else
				echo ""
				echo "  $TG_H_GROUP commands:"
				while IFS= read -r TG_H_VERB; do
					[ -z "$TG_H_VERB" ] && continue
					if [ -n "$(tgCmdArgs "$TG_H_GROUP" "$TG_H_VERB")" ]; then
						echo "    $TG_H_GROUP $TG_H_VERB $(tgCmdArgs "$TG_H_GROUP" "$TG_H_VERB")"
					else
						echo "    $TG_H_GROUP $TG_H_VERB"
					fi
					TG_H_LINE="$(tgCmdSummary "$TG_H_GROUP" "$TG_H_VERB")"
					[ -n "$TG_H_LINE" ] && echo "        $TG_H_LINE"
				done <<< "$(tgCmdGroupVerbs "$TG_H_GROUP")"
			fi
		done
	else
		echo "    (command listing unavailable - data/commands.def not loaded)"
		echo "    see the wiki for the full command reference"
	fi

	echo ""
	echo "  DETAILS:"
	echo ""
	echo "    lang=<option>                    Mostly to get translated configs on inital setup."
	echo "                                      <option> can be a language file name without suffix or an path to a valid language file"
	echo ""
	echo "    (get commands work most reliably for games previously launched with ${PROGNAME,,}:)"
	echo ""
	echo "    proton download variants:"
	echo "                                       - from filerequester"
	echo "                                       - directly from <url>"
	echo "                                       - the 'latest|l' GE version"
	echo "                                       - 'latestge|lge' for Proton-GE"
	echo "                                       - 'latesttkg|ltkg' for Proton-TKG"
	echo ""
	echo "    proton getslr native                (optional) get the native Steam Linux Runtime"
	echo ""
	echo "    steam add-game <args>:"
	echo "     Ensure the Steam Client is closed before adding shortcuts."
	echo "     <args>:                          for cli min arg is'-ep'"
	echo "     -an=|--appname=	                 App Name - optional"
	echo "     -ep=|--exepath=                  Full gamepath required"
	echo "     -sd=|--startdir=                 Start Dir - optional"
	echo "     -ip=|--iconpath=                 Icon Path - optional"
	echo "     -lo=|--launchoptions             Game Launch Options - optional"
	echo "     -hd=|--hide=                     Hide Game - optional*"
	echo "     -adc=|--allowdesktopconf=        Allow Desktop Conf - optional"
	echo "     -ao=|--allowoverlay=             Allow Overlay - optional"
	echo "     -vr=|--openvr=                   OpenVR - optional*"
	echo "     -t=|--tags=                      Tags - quoted, comma-separated - optional"
	echo "     -stllo|--stllaunchoption         Use '${PROGCMD} %command%' as Launch Option - optional"
	echo "     -ct=|--compatibilitytool=        Specify the name of the compatibility tool to use - optional"
	echo "                                       Can specify 'default' to use the global Steam Compatibility Tool"
	echo "     -hr=|--hero=                     Hero Art path    - Banner used on the Game Screen (3840x1240 recommended) - optional"
	echo "     -lg=|--logo=                     Logo Art path    - Logo that gets displayed on Game Screen (16:9 recommended) - optional"
	echo "     -ba=|--boxart=                   Box Art path     - Cover art used in the library (600x900 recommended) - optional"
	echo "     -tf=|--tenfoot=                  Tenfoot Art path - Small banner used for recently played game in library (600x350 recommended) - optional"
	echo "     --copy                            Copy art files to Steam Grid folder (default) - optional"
	echo "     --link                            Symlink art files to Steam Grid folder - optional"
	echo "     --move                            Move art files to Steam Grid folder - optional"
	echo "     --auto-artwork                  Use image files in the game EXE directory with names 'hero', 'logo', 'boxart', 'tenfoot' - optional"
	echo "                                       This will respect the copy method flags above."
	echo "                                       Note also that this will return for any files assumed to be images, even if Steam doesn't support the image format."
	echo "     --use-steamgriddb               Enable searching SteamGridDB for game artwork"
	echo "                                      By default, if no other options are provided, it will search SteamGridDB using --appname"
	echo "                                      If -sgid, -sgai, or -sgnm are passed, this option will automatically be enabled"
	echo "     --steamgriddb-game-name=       Custom name to search and download grid artwork on, if no ID is found it will fall back to Steam AppID OR SteamGridDB Game ID"
	echo "                                      If no IDs are provided and no match is found on the given name, no artwork will be downloaded"
	echo "     --steamgriddb-steam-appid=     Steam AppID to search and download grid artwork on, this will be used instead of SteamGridDB Game ID if both are passed"
	echo "     --steamgriddb-game-id=         Game ID from SteamGridDB to search and download grid artwork on"
	echo "                                        This requires a SteamGridDB API key. See the SteamGridDB wiki page for guidance on how to generate and supply it."
	echo ""
	echo "    game desktop-icon <0-3>:"
	echo "                                       0=only internally"
	echo "                                       1=on the desktop"
	echo "                                       2=for the application menu"
	echo "                                       3=for desktop and application menu"
	echo ""
	echo "    game launcher <args>:"
	echo "             COLLECTION                Show only installed games from Steam collection COLLECTION"
	echo "             menu                      Open Steam Collection Menu"
	echo "             last                      Open last Game as 'Menu'"
	echo "             auto                      Create/Download data for all installed games first"
	echo "             update                    ReCreate all Collection Menus"
	echo "                                       Can be combined with auto"
	echo ""
	echo "    game onetimerun <args>:"
	echo "         --exe=                        Absolute path to the One-Time executable (can be Windows or Linux executable)"
	echo "         --proton=                     Name of the Proton version to use (see tinkergame proton list). Defaults to Per-Game Proton version ('USEPROTON'), ignored if not Windows executable"
	echo "         --workingdir=                 Working directory to launch the executable from"
	echo "         --useexedir                   Use the same directory as the executable as the working directory (overrides --workingdir)"
	echo "         --args=                       Arguments to append to the end of the executable launch"
	echo "         --forceproton                 Use Proton to run executable even if TinkerGame detects doesn't detect it as a Windows executable"
	echo "         --useslr                      Use the Steam Linux Runtime to run the application, if available (uses SLR specified by Proton version or native Linux Steam Linux Runtime)"
	echo "         --save                        Save given configuration for use in the One-Time Run GUI for this game in future"
	echo "         --default                     Restore all saved One-Time Run values to default"
	echo ""
	echo "    game vr <windowname> <SteamAppID> s   's'ave windowname for the game"
	echo ""
	echo "    game waitrequester e|s|u           <e>nable the waitrequester for the launched game"
	echo "                                       (no effect if already enabled)"
	echo "                                     <s>kip the waitrequester temporarily"
	echo "                                     <u>nskip the temporary waitrequester skip"
	echo ""
	echo "    artwork set <gameid> <args>:       By default, given artwork will be copied to the Steam Grid folder"
	echo "                                      Note that only ONE of the copy/link/move options should be used"
	echo "      -hr=|--hero=                     Hero Art path    - Banner used on the Game Screen (3840x1240 recommended)"
	echo "      -lg=|--logo=                     Logo Art path    - Logo that gets displayed on Game Screen (16:9 recommended)"
	echo "      -ba=|--boxart=                   Box Art path     - Cover art used in the library (600x900 recommended)"
	echo "      -tf=|--tenfoot=                  Tenfoot Art path - Small banner used for recently played game in library (600x350 recommended)"
	echo "      --copy                            Copy art files to Steam Grid folder"
	echo "      --link                            Symlink art files to Steam Grid folder"
	echo "      --move                            Move art files to Steam Grid folder"
	echo ""
	echo "    artwork download <args>:           Attempts to search for and download hero, logo, and boxart from SteamGridDB, and can optionally"
	echo "                                      apply this artwork to the game in your Steam library, by giving it the AppID of the game to use"
	echo "                                      in the filename."
	echo "                                       This setting uses preferences specified on Global Menu under SteamGridDB options, such as"
	echo "                                       dimensions, and how to manage existing files (though an override can be specified for how"
	echo "                                       to manage existing artwork files)."
	echo "     Pass an AppID instead of the below args to open a GUI for selecting game artwork."
	echo "      <args>:"
	echo "      --search-id=                     Steam AppID or SteamGridDB Game ID to search for (ex: AppID 22330 or Game ID 5258102)"
	echo "      --search-name=                   Search SteamGridDB with a name and return the best-match Game ID, and use --nonsteam automatically."
	echo "                                        You must pass '--filename-appid' when using this option, otherwise artwork will use the wrong ID"
	echo "      --filename-appid=                Steam AppID to use when naming the file, only required when searching on Game ID or Game Name so the artwork is applied to the correct Shortcut"
	echo "      --steam                          The Search ID passed is for a Steam AppID (default)"
	echo "      --nonsteam                       The Search ID passed is for a SteamGridDB Game ID"
	echo "      --apply                          Apply the downloaded game artwork to the Steam game (if not set, artwork will be downloaded to TinkerGame Grid directory only)"
	echo "      --no-apply                       Don't apply the downloaded game artwork (artwork will be downloaded to TinkerGame Grid directory only)"
	echo "      --skip-existing                  Skip setting artwork for this game if it already has custom artwork"
	echo "      --replace-existing               Replace existing artwork files for this game -- they cannot be recovered later"
	echo "      --backup-existing                Backup existing artwork files for this game before replacing them, so they can be restored"
	echo ""
	echo "    steam shared <opts>:               Steamworks Shared:"
	echo "      <l>                              List packages - or"
	echo "      <i>                              Install package with options:"
	echo "      <packagename>                    - packagename"
	echo "      <SteamAppID or pfx>              - SteamAppID or pfx path"
	echo "      <wine binary>                    - Optional wine binary path"
	echo ""
	echo "    update details:"
	echo "           gamedata <SteamAppID>       Updates missing desktopfiles"
	echo "                                       and pictures of installed games"
	echo "                                       or only from <SteamAppID>"
	echo "           grid <SteamAppID>         Update Steam Grid for installed game(s)"
	echo "                                       optional argument either a SteamAppID,"
	echo "                                       'owned', 'installed', or 'nonsteam|shortcut'"
	echo "                                       (default is 'installed')"
	echo "           allgamedata                 The same as above for"
	echo "                                       all games in $SCV"
	echo "           shaders <shadername>        all enabled shaders or <shadername>"
	echo "                                       'list' to list shaders"
	echo "                                       'repos' to update used shader repos"
	echo "           gameshaders <opt1> <opt2|3> open shader selection for dir <opt1>,"
	echo "                                       for last gamedir when <opt1> is empty"
	echo "                                       enable repo <opt1> for dir <opt2>"
	echo "                                        with empty <opt3> or <opt3>=enable"
	echo "                                       disable repo <opt1> for dir <opt2>"
	echo "                                        with  <opt3>=disable"
	echo "                                       block repo <opt1> with <opt2>=block"
	echo "                                       unblock repo <opt1> with <opt2>=unblock"
	echo "           reshade <version>           (re)-download ReShade (version)"
	echo ""
	echo "    meta raw|write <id|i|o>:           (takes a long time for many games!)"
	echo "                                       Append any arg to update the raw file/metadata"
	echo ""
	echo "    mods mo2 <sub>:"
	echo "         create-instance|ci <id>     create MO2 instance for <id>"
	echo "         download|d                  download latest MO2 release"
	echo "         getprefix|gp                Output path to MO2 prefix"
	echo "         install|i                   install MO2 (includes download)"
	echo "          <path>                      optional path for custom MO2 installer executable"
	echo "         list-supported|ls           list games supported by MO2"
	echo "         list-installed|li           list installed games supported by MO2"
	echo "         repairpfx                    Experimental: attempt to repair the MO2 prefix"
	echo "         resetmime                   (Re)set MimeType and application menu entries"
	echo "         start|s                     start MO2 (includes download+install)"
	echo "         url|u <url>                 open nxm url with MO2"
	echo "         winecfg                     Run Winecfg with MO2 Wine in MO2 prefix"
	echo "         winetricks|wt               Run Winetricks with MO2 Wine in MO2 prefix"
	echo ""
	echo "    mods vortex <sub>:                 ${VTX} download, install, and start can optionally take"
	echo "                                       a version tag to download."
	echo "                                       Ex: tinkergame mods vortex start v1.8.0"
	echo "           getprefix|gp                Output path to Vortex prefix"
	echo "           install                     Installs ${VTX^}"
	echo "           list-supported|ls           List all ${VTX^}-supported Steam Game IDs"
	echo "                                       (offline - ${VTX^} needs to be installed)"
	echo "           list-online|lo              List ${VTX^}-supported games found online"
	echo "           list-owned|low              List owned games with ${VTX^} support"
	echo "           list-installed|li           List installed Games with ${VTX^} support"
	echo "           games                       Gui to en/disable ${VTX^} for supported game"
	echo "           symlinks                    Gui showing ${VTX^} symlinks"
	echo "           start                       Starts ${VTX^}"
	echo "           url|u <url>                 Open nxm url with ${VTX^}"
	echo "           getset                      Show config of installed ${VTX^}"
	echo "           reset                       Reset all autodetected settings in ${VTX^}"
	echo "           stage <path>                Add ${VTX^} stage via dialog"
	echo "                                        or directly the one given in <path>"
	echo "           resetmime                   (Re)set MimeType and application menu entries"
	echo "           winecfg                     Run Winecfg with ${VTX^} Wine in ${VTX^} prefix"
	echo "           winetricks|wt               Run Winetricks with ${VTX^} Wine in ${VTX^} prefix"
	echo ""
	echo "    mods hedge <sub>:                  HedgeModManager"
	echo "            install|i                  install latest stable HedgeModManager"
	echo "            download|d <channel>       download latest HedgeModManager release (stable or nightly)"
	echo "                                        defaults to stable"
	echo "            start|s <channel>          start HedgeModManager"
	echo "                                        automatically downloads and installs latest stable if <channel>"
	echo "                                        is not provided"
	echo "            start|s <channel> --force  force dotnet48 reinstall for each installed 64bit HMM game"
	echo "            url|u <url>              Download a GameBanana mod using MineType URL"
	echo "                                      Note that this will *not* work with regular browser URLs"
	echo "            desktopfile|df           (Re-)create .desktop files for HedgeModManager"
	echo "            list-supported           List games supported by HedgeModManager"
	echo "            list-installed           List installed games with HedgeModManager support"
	echo "            list-owned               List owned games on Steam with HedgeModManager support"
	echo "            resetmime                (Re)set MimeType and application menu entries"
	echo "            uninstall                Remove HedgeModManager downloads folder, desktop files and Wineprefix"
	echo "                                      Note that this will not remove your mods or installed Winetricks"
	echo ""
	echo "    config yad <yad binary> <opt>:     <yad binary> can be either"
	echo "                                       <absolute/path>"
	echo "                                       <conty>"
	echo "                                       <ai> or <appimage> plus optional <opt>:"
	echo "                                       <opt> can be either"
	echo "                                         <absolute/path/to/a/yad/appimage>"
	echo "                                         <http/s/yad/appimage/download/url>"
	echo "                                       (see Wiki for details)"
	echo ""
	echo "    list note:                        Non-Steam Games will NOT be included in <installed,owned>,"
	echo "                                       they will only show up for <non-steam|nsg>"
}
